import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0D0F12',
  },
  scannerContainer: {
    flex: 1,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewfinder: {
    width: width * 0.75,
    height: width * 0.75,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: 'rgba(194, 255, 26, 0.3)',
    backgroundColor: 'rgba(22, 24, 28, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  // Viewfinder Corner Accents
  cornerTL: {
    position: 'absolute',
    top: 16,
    left: 16,
    width: 24,
    height: 24,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderColor: '#C2FF1A',
    borderTopLeftRadius: 8,
  },
  cornerTR: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 24,
    height: 24,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderColor: '#C2FF1A',
    borderTopRightRadius: 8,
  },
  cornerBL: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    width: 24,
    height: 24,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderColor: '#C2FF1A',
    borderBottomLeftRadius: 8,
  },
  cornerBR: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    width: 24,
    height: 24,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderColor: '#C2FF1A',
    borderBottomRightRadius: 8,
  },
  scannerLine: {
    position: 'absolute',
    top: 0,
    width: '90%',
    height: 3,
    backgroundColor: '#C2FF1A',
    // Glow effect
    shadowColor: '#C2FF1A',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 5,
  },
  overlayTop: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : 45,
    left: 20,
    right: 20,
    alignItems: 'center',
  },
  overlayTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  overlaySubtitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8E939E',
    marginTop: 6,
    textAlign: 'center',
    backgroundColor: 'rgba(22, 24, 28, 0.7)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    overflow: 'hidden',
  },
  hudContainer: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 140 : 124,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(22, 24, 28, 0.85)',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: '#24272D',
  },
  hudHeader: {
    fontSize: 11,
    fontWeight: '800',
    color: '#C2FF1A',
    letterSpacing: 0.5,
    marginBottom: 8,
    textAlign: 'center',
  },
  hudRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  hudItem: {
    alignItems: 'center',
  },
  hudValue: {
    fontSize: 14,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  hudLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#8E939E',
    marginTop: 2,
  },
  controlsRow: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 240 : 224,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  shutterButton: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: '#FFFFFF',
    borderWidth: 6,
    borderColor: '#16181C',
    alignItems: 'center',
    justifyContent: 'center',
    // Glow shadow
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  shutterInner: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#C2FF1A',
  },
  viewfinderImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    borderRadius: 30,
  },
  resultOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    padding: 24,
    justifyContent: 'center',
    zIndex: 100,
  },
  resultCard: {
    borderRadius: 28,
    borderWidth: 1,
    padding: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  resultHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  resultFoodName: {
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  resultRoastBox: {
    borderRadius: 16,
    padding: 16,
    marginVertical: 16,
  },
  resultRoastText: {
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  resultMacrosRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 16,
  },
  resultMacroCol: {
    alignItems: 'center',
    flex: 1,
  },
  resultMacroVal: {
    fontSize: 18,
    fontWeight: '900',
  },
  resultMacroLbl: {
    fontSize: 10,
    fontWeight: '700',
    marginTop: 4,
  },
  resultIngredientsTitle: {
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 8,
  },
  resultIngredientsList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 24,
  },
  resultIngredientTag: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  resultIngredientText: {
    fontSize: 11,
    fontWeight: '700',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  buttonFlex: {
    flex: 1,
  },
  galleryButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
  },
  controlsRowWithGallery: {
    position: 'absolute',
    bottom: Platform.OS === 'ios' ? 240 : 224,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    gap: 24,
  },
  cameraView: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  permissionPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  permissionText: {
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 18,
  },
  permissionBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
});
